const swaggerUi = require('swagger-ui-express');
const swaggerJsDoc = require('swagger-jsdoc');

const options = {
    swaggerDefinition: {
      // Like the one described here: https://swagger.io/specification/#infoObject
      info: {
        title: 'TACT Backend Server',
        version: '6.0.0',
        description: ' Express REST API with autogenerated swagger doc',
      },
    },
    // List of files to be processes. You can also set globs './routes/*.js'
    apis: ['./routes/fund-routes.js'],
  };

  module.exports = (app) => {
      app.use("/tact-rest-api-docs/",swaggerUi.serve, swaggerUi.setup(options) );
  }